name: Build TDMSViewer Installer

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: python -m venv venv
      shell: cmd

    - name: Activate venv and install dependencies
      run: |
        pip freeze
        call venv\Scripts\activate.bat
        python -m pip install --upgrade pip
        pip install -r TDMSViewer/requirements.txt
        pip install pyinstaller
        pip freeze
      shell: cmd

    - name: Print installed packages
      run: |
        call venv\Scripts\activate.bat
        pip freeze
      shell: cmd
      
    - name: Clean previous builds
      run: |
        Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue
        Remove-Item TDMSViewerApp.spec -ErrorAction SilentlyContinue
      shell: pwsh

    - name: Generate PyInstaller EXE
      run: |
        call venv\Scripts\activate.bat
        python -m PyInstaller --onefile --windowed TDMSViewer/TDMSViewer.py --name TDMSViewerApp
      shell: cmd

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Build installer with Inno Setup
      run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss'
      shell: pwsh

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: TDMSViewerInstaller
        path: Output/TDMSViewerSetup.exe
        retention-days: 1