name: Build Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller nptdms matplotlib

    - name: Build with PyInstaller
      run: pyinstaller --noconfirm --onefile --windowed TDMSViewer\TDMSViewer.py

    - name: Download Inno Setup
      run: |
        Invoke-WebRequest https://jrsoftware.org/download.php/is.exe -OutFile is.exe
        Start-Process is.exe -ArgumentList '/VERYSILENT' -Wait

    - name: Run Inno Setup
      run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss'

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TDMSViewerInstaller
        path: Output\TDMSViewerSetup.exe
